# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"Y\n\x0fGenerateRequest\x12\n\n\x02qa\x18\x01 \x03(\t\x12\x13\n\x0brag_results\x18\x02 \x03(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\x16\n\x0e\x63haracter_type\x18\x04 \x01(\x05\" \n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2O\n\nLLMService\x12\x41\n\x0eGenerateStream\x12\x14.llm.GenerateRequest\x1a\x15.llm.GenerateResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=18
  _globals['_GENERATEREQUEST']._serialized_end=107
  _globals['_GENERATERESPONSE']._serialized_start=109
  _globals['_GENERATERESPONSE']._serialized_end=141
  _globals['_LLMSERVICE']._serialized_start=143
  _globals['_LLMSERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
